version: "3.8"
services:
  db:
    image: mongo:latest@sha256:9d2f56b066370e614cc6edcd975aba5ac1926c24e63d10bcf8f626bbf75dfdff
    container_name: db
    ports:
      - 27017:27017
  server:
    build: server
    container_name: server
    ports:
      - 5000:5000
    environment:
      - DB_HOST=db
      - DB_PORT=27017
      - PORT=5000
    depends_on:
      - db
