version: "3.8"
services:
  server:
    container_name: server
    build: server
    ports:
      - 5000:5000
    healthcheck:
      test: curl --fail http://localhost:5000/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 3s