version: "3.8"
services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
  postgres:
    image: postgres:alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  nginx:
    build: nginx
    container_name: nginx
    command: nginx -g 'daemon off;'
    depends_on:
      - api
    ports:
      - 80:80
  api:
    build: server
    container_name: api
    depends_on:
      - redis
      - postgres
    command: node index.js