version: "3.8"
services:
  db:
    container_name: db
    image: mongo:4.1.13
    ports:
      - 27019:27017
    networks:
      - net_A
    volumes:
      - mongovol:/data/db
  server:
    container_name: server
    build: server
    ports:
      - 3003:3003
    networks:
      - net_A
    depends_on:
      - db
volumes:
  mongovol:
    name: mongovol
networks:
  net_A:
    name: net_A
    external: false